### ISSUE TITLE
A new error in the discourse/publish-rubygems-action@v2-beta fork

### ISSUE THREAD

**Issue by lmrodriguezr** [cadwallion/publish-rubygems-action#20]
Dear @cadwallion, I believe you're also the maintainer of the discourse/publish-rubygems-action fork, right?

I have been using this action for a while now and it works great! However, a new error is now creeping up and I have no idea where it's coming from. I believe the relevant error message is:
```
+ exec rake release
miga-base 1.2.15.3 built to pkg/miga-base-1.2.15.3.gem.
rake aborted!
There are files that need to be committed first.
/usr/local/bundle/gems/bundler-2.4.6/lib/bundler/gem_helper.rb:168:in `guard_clean'
/usr/local/bundle/gems/bundler-2.4.6/lib/bundler/gem_helper.rb:72:in `block in install'
Tasks: TOP => release => release:guard_clean
(See full trace by running task with --trace)
```

This is the full job error (with debug on):
https://github.com/bio-miga/miga/actions/runs/4113928545/jobs/7100801289

I also tried using v2 (instead of v2-beta), and I get the same error:
https://github.com/bio-miga/miga/actions/runs/4114053883/jobs/7101006995

This exact same pipeline was working wonderfully before (last time I used it was two weeks ago). The changes in that commit are rather minor, so I don't think the changes I introduced are what is causing the failure.

Any help is greatly appreciated!
Miguel.

**Comment by lmrodriguezr** [comment]
BTW, sorry for the rather uninformative issue title, but I have no idea what's the actual failure :/

**Comment by skcc321** [comment]
can be related to the missing `git config --global --add safe.directory "$GITHUB_WORKSPACE"` in entry_point.sh

**Comment by lmrodriguezr** [comment]
Thank you @skcc321 ! Indeed, I was able to fix it setting the safe directory: https://github.com/discourse/publish-rubygems-action/pull/7
